[tool.black]

[tool.isort]
profile = "black"
skip_gitignore = true

[tool.mypy]
ignore_missing_imports = true
exclude = "venv/*"

[tool.pytest.ini_options]
testpaths = "tests"
pythonpath = "."
filterwarnings = ["ignore:::DtypeWarning"]

[tool.ruff]
line-length = 140
lint.ignore = ["E203", "E266"] #, "E501"]
lint.unfixable = ["F841", "F401", "E731"]
include = ["*.py", "src/*", "/tests/*"]
exclude = [
    "data/",
    ".mypy_cache/",
    ".pytest_cache/",
    "venv/",
    "*.ipynb",
    "*.ini",
]

[tool.vulture]
exclude = [".venv/"]
make_whitelist = true
min_confidence = 80
sort_by_size = true
verbose = false
